---
- name: Change directory ownerships
  file:
    path: "{{ item }}"
    owner: "{{ tomcat_unixuser }}"
    group: "{{ tomcat_unixgroup }}"
    recurse: yes
  with_items:
    - "{{ shib_installdir }}/shibboleth-idp"
    - "{{ java_installdir }}/{{ jdk_directory }}"
    - "{{ tomcat_installdir }}/apache-tomcat-{{ tomcat_version }}"