---
    - name: Install apache, mod_ssl, wget, vim, git, unzip, libsemanage (Python)
      yum: pkg={{ item }} state=present
      with_items:
      - vim-enhanced
      - httpd
      - mod_ssl
      - wget
      - unzip
      - git
      - libsemanage-python

    - name: Create download directory
      file: path={{ download_dir }} state=directory

    - name: Create secure directory
      file: path=/var/www/html/secure state=directory

    - name: Download java
      command: 'wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" {{ jdk_archive_url }} -O {{ download_dir }}/{{ jdk_archive }}'

    - name: Download JCE
      command: 'wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" {{ jce_archive_url }} -O {{ download_dir }}/{{ jce_archive }}'

    - name: Create profile.d files
      template: src=profile.d/{{ item.src }} dest=/etc/profile.d/{{ item.dest }}
      with_items:
        - { src: 'java.sh.j2', dest: 'java.sh' }
        - { src: 'maven.sh.j2', dest: 'maven.sh' }
