---
    - name: Install apache, mod_ssl, wget, vim, git, unzip, libsemanage (Python)
      yum: pkg={{ item }} state=present
      with_items:
      - vim-enhanced
      - httpd
      - mod_ssl
      - wget
      - unzip
      - git
      - libsemanage-python

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Create download directory
      file: path={{ download_dir }} state=directory

    - name: Create secure directory
      file: path=/var/www/html/secure state=directory

    - name: Download OpenJDK
      get_url:
        url: "{{ jdk_archive_url }}"
        dest: "{{ download_dir }}/{{ jdk_archive }}"
        checksum: "{{ jdk_archive_checksum }}"

    - name: Create profile.d files
      template: src=profile.d/{{ item.src }} dest=/etc/profile.d/{{ item.dest }}
      with_items:
        - { src: 'java.sh.j2', dest: 'java.sh' }
        - { src: 'maven.sh.j2', dest: 'maven.sh' }
