---
download_dir: /opt/download
tomcat_unixgroup: tomcat
tomcat_unixgid: 1002
tomcat_unixuser: tomcat
tomcat_unixuid: 1002
tomcat_installdir: /opt
tomcat_servicename: tomcat
shib_idp_version: 3.3.3
shib_installdir: /opt
shib_home: "{{ shib_installdir }}/shibboleth-idp/"
java_installdir: /opt
jdk_archive: zulu8.31.0.1-jdk8.0.181-linux_x64.tar.gz
jdk_archive_checksum: md5:64270772bfaaced5611d754cd022c32e
jdk_archive_url: "https://cdn.azul.com/zulu/bin/{{ jdk_archive }}"
jdk_directory: zulu8.31.0.1-jdk8.0.181-linux_x64
maven_installdir: /opt
maven_version: 3.5.4
tomcat_version: 8.5.34
totp_installdir: /opt
totp_version: 0.5.1
ldap_url: "ldap://localhost:389"
ldap_base_dn: ou=People,dc=vagrant,dc=local
ldap_manager: cn=manager,dc=vagrant,dc=local
ldap_password: Password1
