---
download_dir: /opt/download
tomcat_unixgroup: tomcat
tomcat_unixgid: 1002
tomcat_unixuser: tomcat
tomcat_unixuid: 1002
tomcat_installdir: /opt
tomcat_servicename: tomcat
shib_idp_version: 3.2.0
shib_installdir: /opt
shib_home: "{{ shib_installdir }}/shibboleth-idp/"
java_installdir: /opt
jdk_archive: jdk-8u172-linux-x64.tar.gz
jdk_archive_url: "http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/{{ jdk_archive }}"
jdk_directory: jdk1.8.0_172
jce_archive: jce_policy-8.zip
jce_archive_url: "http://download.oracle.com/otn-pub/java/jce/8/{{ jce_archive }}"
maven_installdir: /opt
maven_version: 3.5.4
tomcat_version: 8.5.32
totp_installdir: /opt
totp_version: 0.5.1
ldap_url: "ldap://localhost:389"
ldap_base_dn: ou=People,dc=vagrant,dc=local
ldap_manager: cn=manager,dc=vagrant,dc=local
ldap_password: Password1
