---
# handlers file for totp-authenticator

    - name: restart tomcat
      service: name={{ tomcat_servicename }} state=restarted

    - name: stop tomcat
      service: name={{ tomcat_servicename }} state=stopped

    - name: start tomcat
      service: name={{ tomcat_servicename }} state=started
