---
- hosts: all
  sudo: true
  vars_files:
    - ../../provisioning/vars/variables.yml

  tasks:
    - include: ../../provisioning/tasks/environment.yml
    - include: ../../provisioning/tasks/tomcat.yml
    - include: ../../provisioning/tasks/shibboleth-idp.yml
    - include: ../../provisioning/tasks/shibboleth-sp.yml
    - include: ../../provisioning/tasks/httpd.yml
    - include: ../../provisioning/tasks/post.yml
