---
    - name: Chowning dirs shib
      command: 'chown -R tomcat:tomcat /opt/shibboleth-idp'

    - name: Chowning dirs java
      command: 'chown -R tomcat:tomcat /opt/jdk1.8.0_45'

    - name: Chowning dirs tomcat
      command: 'chown -R tomcat:tomcat /opt/apache-tomcat-{{ tomcat_version.stdout }}'
