---

  - name: Create tomcat group
    group: name=tomcat state=present gid=1000

  - name: Create tomcat user
    user: name=tomcat comment="tomcat" uid=1000 group=tomcat state=present

  - name: Download tomcat
    get_url: url=http://archive.apache.org/dist/tomcat/tomcat-8/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz dest=/opt/download/apache-tomcat-{{ tomcat_version }}.tar.gz

  - name: Eextract tomcat
    unarchive: src=/opt/download/apache-tomcat-{{ tomcat_version }}.tar.gz dest=/opt/ copy=no

  - name: Extract java
    unarchive: src=/opt/download/jdk-8u45-linux-x64.tar.gz dest=/opt/ copy=no

  - name: Create java symlink
    file: path=/opt/java
          src=/opt/jdk{{ java_version}}
          state=link 
          force=yes

  - name: Extract jce
    command: 'unzip -oj /opt/download/jce_policy-8.zip -d /opt/jdk{{ java_version }}/jre/lib/security/'

  - name: Copy Tomcats server.xml
    template: src=server.xml.j2 dest=/opt/apache-tomcat-{{ tomcat_version }}/conf/server.xml

  - name: Tomcat Init script
    template: src=tomcat.j2 dest=/etc/init.d/tomcat owner=root group=root mode=0755

  - name: Enable service tomcat
    shell: chkconfig --add tomcat
